name: dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/Xaqiri/WAIIG

environment:
  sdk: ^3.0.6

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
